src/components/blocks/confirmation-modal/confirmation-modal.tsx, src/components/ui/alert-dialog.tsx, src/features/profile/component/general-info/general-info.tsx, src/features/profile/component/modals/edit-profile/edit-profile.tsx, src/features/profile/component/modals/update-password/update-password.tsx, src/pages/main/iam-table.tsx
- Urgent responsive issue on small devices
- Disabled the scrolling when the UserDetail sheet is open
=> [RUSH] Urgent fixes on the responsive on small devices

src/components/ui/alert-dialog.tsx, src/components/ui/sheet.tsx, src/features/Iam/components/user-details/user-details.tsx, src/features/profile/component/modals/edit-profile/edit-profile.tsx, src/pages/profile/profile.tsx
- Minor UI fixes on adjustment in the responsive mobile view 
- Fixed the length of the Sheet Content issue
- Fixed the phone number length validation and isphoneNumber is valid or not w.r.t country code selected
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/95
=> [RUSH 05/02/2025]: Minor Changes in responsive + minor code clean up + Country code validation

src/components/blocks/data-table/data-table-date-filter.tsx, src/components/blocks/layout/app-sidebar.tsx, src/components/blocks/u-profile-menu/u-profile-menu.tsx, src/components/core/theme-provider.tsx, src/components/ui/calendar.tsx, src/features/inventory/component/advance-data-table/advance-data-table.tsx, src/features/inventory/component/advance-expand-row-content/advance-expand-row-content.tsx, src/features/inventory/component/advance-table-columns/advance-table-columns.tsx, src/features/inventory/component/advance-table-filter-toolbar/advance-table-filter-toolbar.tsx, src/features/inventory/component/last-updated-filter-dropdown/last-updated-filter-dropdown.tsx, src/features/inventory/component/stock-filter-dropdown/stock-filter-dropdown.tsx
- SonarQube warning issue fixes
- Advance inventory table extendable content action button fixed position
- Advance inventory table revamp
- Fixed the Date Picker edge cases 
- Fixed the stock and lastupdate dropdown reset filter from top level component
=> [RUSH 01/03/2025] Resolve the SonarQube issue and resolve advance table edge cases

src/components/blocks/data-table/data-table-column-header.tsx, src/components/blocks/data-table/data-table-date-filter.tsx, src/components/blocks/data-table/data-table-faceted-filter.tsx, src/components/blocks/data-table/data-table-pagination.tsx, src/components/blocks/data-table/data-table-view-options.tsx, src/components/blocks/data-table/data-table.tsx, src/features/iam/components/iam-table/iam-table-row-actions.tsx, src/features/iam/components/iam-table/iam-table-toolbar.tsx, src/features/inventory/component/advance-data-table/advance-data-table.tsx, src/features/inventory/component/advance-table-columns-toolbar/advance-table-columns-toolbar.tsx, src/features/inventory/component/advance-table-filter-toolbar/advance-table-filter-toolbar.tsx, src/features/inventory/component/advance-table-view-options/advance-table-view-options.tsx, src/features/inventory/component/last-updated-filter-dropdown/last-updated-filter-dropdown.tsx, src/features/inventory/component/stock-filter-dropdown/stock-filter-dropdown.tsx, src/lib/https.ts, src/pages/inventory/inventory.tsx, src/styles/globals.css
Closes  https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/167
=> [RUSH 05/03/2025] Resolved the SonarQube issues + Push the solution to the column pinned styling issue

src/components/blocks/data-table/data-table-view-options.tsx, src/components/ui/calendar.tsx, src/components/ui/chart.tsx, src/components/ui/command.tsx, src/components/ui/label.tsx, src/components/ui/popover.tsx, src/components/ui/radio-group.tsx, src/components/ui/scroll-area.tsx, src/components/ui/separator.tsx, src/components/ui/sheet.tsx, src/components/ui/switch.tsx, src/components/ui/tabs.tsx, src/components/ui/tooltip.tsx, src/features/inventory/component/advance-data-table/advance-data-table.tsx, src/features/inventory/component/advance-table-columns/advance-table-columns.tsx, src/state/query-client/index.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/187
@afiapreety Removing 'use client' since it's not needed in React 18. This directive is specific to Next.js, though React 19 now includes a similar feature.
=> [RUSH 10/03/2025] Resolved the some of the SonarQube issue in Advance Table

src/components/blocks/confirmation-modal/confirmation-modal.tsx, src/components/ui/dialog.tsx, src/components/ui/select.tsx, src/features/iam/components/add-profile/add-profile.spec.tsx, src/features/iam/components/add-profile/add-profile.tsx, src/features/iam/components/iam-table/iam-table-row-actions.tsx, src/features/iam/components/user-details-mobile-view/expanded-user-details.tsx, src/features/iam/components/user-details/user-details.tsx, src/features/profile/component/modals/edit-iam-profile-details/edit-iam-profile-details.css, src/features/profile/component/modals/edit-iam-profile-details/edit-iam-profile-details.tsx, src/features/profile/hooks/use-account.ts, src/features/profile/services/accounts.service.ts, src/features/profile/utils/utils.ts, src/pages/main/iam-table.tsx
=> [FE] Add user, Update user designs with api integration on IAM Table

package-lock.json, src/pages/main/dashboard/dashboard.tsx
for now we won't be implementing this modal as discussed with @kazi-lakit only design is fine.
=> Commented out the mfa popup logic for now

package-lock.json, src/features/auth/components/signin-form/signin-form.tsx, src/features/auth/services/auth.service.ts, src/features/profile/component/modals/authenticator-app-setup/authenticator-app-setup.tsx, src/features/profile/component/modals/email-verification/email-verification.tsx, src/features/profile/component/modals/manage-two-factor-authentication/manage-two-factor-authentication.tsx, src/features/profile/component/modals/two-factor-authentication-setup/two-factor-authentication-setup.tsx, src/features/profile/hooks/use-mfa.ts, src/features/profile/services/mfa.services.ts, src/features/profile/types/mfa.types.ts, src/hooks/use-resend-otp.ts, src/pages/auth/verify-otp-key/verify-otp-key.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/293
=> [URGENT 10/04/2025]: Revise MFA flow with new backend endpoint and change the functionality in whole MFA flow

src/features/task-manager/components/card-view/column-menu.tsx, src/features/task-manager/components/card-view/tag-drag-overlay.tsx, src/features/task-manager/components/card-view/task-card.tsx, src/features/task-manager/components/card-view/task-column.tsx, src/features/task-manager/components/list-view/drag-overlay-item.tsx, src/features/task-manager/components/list-view/sortable-task-Item.tsx, src/features/task-manager/components/status-circle/status-circle.tsx, src/features/task-manager/components/task-details-view/task-details-view.tsx, src/features/task-manager/data/sample-tasks.ts, src/features/task-manager/hooks/use-task-board.ts, src/features/task-manager/hooks/useTasks.ts, src/features/task-manager/services/convert-task.ts, src/features/task-manager/services/task-service.ts, src/features/task-manager/types/task.ts, src/pages/main/dashboard/dashboard.spec.tsx, src/pages/main/dashboard/dashboard.tsx, src/pages/task-manager/task-card-view.tsx, src/pages/task-manager/task-list-view.tsx
=> All Changes for Task Manger ui bugs  from Afia's side

src/components/ui/popover.tsx, src/features/big-calendar/components/modals/add-event/add-event.tsx, src/features/big-calendar/components/modals/edit-event/edit-event.tsx, src/features/big-calendar/utils/date-utils.ts, src/styles/globals.css
Close https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/342
=> [RUSH 18/04/2025] Revamp the time picker and code refactor

src/features/big-calendar/components/event-participant/event-participant.tsx, src/features/big-calendar/components/modals/edit-event/edit-event.tsx, src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/big-calendar/components/modals/event-invitation/event-invitation.tsx, src/features/big-calendar/components/modals/update-recurring-event/update-recurring-event.tsx, src/features/big-calendar/hooks/use-calendar-events.ts, src/features/big-calendar/types/calendar-event.types.ts
- Improve edit and update recurring events flow like delete recurring events flow
- Fixes minor issue in the mobile view
=> [RUSH 25/04/2025] Improve edit Recurring events flow and Minor fixes in mobile view 

src/features/activity-log-v1/components/activity-log-timeline/activity-log-timeline.tsx, src/features/activity-log-v2/components/activity-log-timeline/activity-log-timeline.tsx, src/features/task-manager/components/card-view/task-card.tsx, src/features/task-manager/components/list-view/sortable-task-Item.tsx, src/features/task-manager/components/task-details-view/attachment-section.tsx, src/features/task-manager/components/task-details-view/editable-heading.tsx, src/features/task-manager/components/task-details-view/task-details-view.tsx, src/features/task-manager/components/task-manager-filters-sheet/task-manager-filters-sheet.tsx, src/features/task-manager/components/task-manager-toolbar/task-manager-toolbar.tsx, src/features/task-manager/contexts/task-context.tsx, src/pages/task-manager/task-list-view.tsx
=> [RUSH 27/04/2025] Refactored Task Manager Known Issues

src/features/big-calendar/components/modals/add-event/add-event.tsx, src/features/big-calendar/components/modals/edit-event/edit-event.tsx
Close https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/430
=> [RUSH 28/04/2025] Minor fixes in the calendar 

src/components/core/dynamic-breadcrumb/dynamic-breadcrumb.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/432
=> [RUSH 28/04/2025] Hid the single level breadcrumb title

src/constant/sidebar-menu.spec.ts, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.spec.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/502
=> [RUSH 08/05/2025] Resolved the SonarQube assigned to me

src/App.tsx, src/components/blocks/layout/app-sidebar.tsx, src/components/blocks/layout/sidebar-menu-Item.tsx, src/components/blocks/u-profile-menu/u-profile-menu.tsx, src/constant/sidebar-menu.spec.ts, src/constant/sidebar-menu.ts, src/features/dashboard/component/dashboard-overview/dashboard-overview.spec.tsx, src/features/dashboard/component/dashboard-overview/dashboard-overview.tsx, src/features/dashboard/component/dashboard-system-overview/dashboard-syetem-overview.spec.tsx, src/features/dashboard/component/dashboard-system-overview/dashboard-system-overview.tsx, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.spec.tsx, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.tsx, src/features/dashboard/component/dashboard-user-platform/dashboard-user-platform.spec.tsx, src/features/dashboard/component/dashboard-user-platform/dashboard-user-platform.tsx, src/features/dashboard/services/dashboard-service.ts, src/i18n/i18n.ts, src/i18n/language-context.tsx, src/i18n/route-module-map.ts, src/pages/main/dashboard/dashboard.spec.tsx, src/pages/main/dashboard/dashboard.tsx
- Fixed the loading issue of language in the translation
- Implementing the translation in the dashboard
- Implementing the translation in the sidebar
- Implementing the translation in the Profile dropdown menu
Close https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/460 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/514 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/519
=> [RUSH 12/05/2025] Translation implement in Dashboard and Loading issue fixes 

src/features/big-calendar/components/calendar-toolbar/calendar-toolbar.tsx, src/features/big-calendar/components/modals/add-event/add-event.tsx, src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/big-calendar/components/modals/event-details/event-details.tsx, src/features/big-calendar/components/modals/event-invitation/event-invitation.tsx, src/features/big-calendar/constants/calendar.constants.ts, src/pages/calendar/calendar.tsx
- language changes in the calendar
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/467
=> [RUSH 14/05/2025] Language integration changes of calendar

src/components/blocks/language-selector/hooks/use-language.ts
- Caching the languages listing
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/540
=> [RUSH 19/05/2025] Caching the languages listing

src/App.tsx, src/components/blocks/language-selector/language-selector.tsx, src/components/core/dynamic-breadcrumb/dynamic-breadcrumb.tsx, src/components/ui/breadcrumb.tsx, src/components/ui/menubar.tsx, src/features/big-calendar/components/agenda-content/agenda-content.tsx, src/features/big-calendar/components/big-calendar/big-calendar.css, src/features/big-calendar/components/big-calendar/big-calendar.tsx, src/features/big-calendar/components/color-picker-tool/color-picker-tool.tsx, src/features/big-calendar/components/modals/add-event/add-event.tsx, src/features/big-calendar/components/modals/edit-event/edit-event.tsx, src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/big-calendar/components/show-more/show-more.tsx, src/features/big-calendar/contexts/calendar-settings.context.tsx, src/features/big-calendar/enums/calendar.enum.ts, src/features/big-calendar/hooks/use-calendar-ui.ts, src/features/big-calendar/index.ts, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.spec.tsx, src/features/email/component/email-ui/email-input.tsx, src/features/email/component/email-ui/email-text-editor.tsx, src/features/email/component/email-view/email-single-action.tsx, src/features/email/component/email-view/email-view-grid/email-view-grid.tsx, src/features/email/component/email-view/email-view-mobile/email-view-mobile.tsx, src/features/profile/component/modals/manage-two-factor-authentication/manage-two-factor-authentication.tsx, src/features/task-manager/components/task-manager-toolbar/task-manager-toolbar.tsx, src/features/task-manager/contexts/task-context.tsx, src/i18n/language-context.tsx, src/pages/auth/signup/signup-page.tsx, src/pages/email/email.tsx, src/pages/task-manager/task-card-view.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/543
=> [RUSH 21/05/2025] Resolve the sonarQube issues 

src/features/big-calendar/components/big-calendar/big-calendar.css, src/features/big-calendar/components/modals/add-event/add-event.tsx, src/features/big-calendar/components/modals/edit-event/edit-event.tsx, src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/big-calendar/components/modals/event-details/event-details.tsx, src/features/big-calendar/components/modals/event-invitation/event-invitation.tsx, src/features/big-calendar/components/year-content/year-content.tsx, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.tsx, src/features/dashboard/component/dashboard-user-platform/dashboard-user-platform.tsx, src/features/email/component/email-compose/email-compose.tsx, src/features/email/component/email-list/email-list.tsx, src/features/email/component/email-ui/email-text-editor.tsx, src/features/email/component/email-view/email-view-grid/email-view-grid.tsx, src/features/email/component/email-view/email-view-mobile/email-view-mobile.tsx, src/features/finance/components/finance-revenue-expense-graph/finance-revenue-expense-graph.tsx, src/features/profile/component/modals/two-factor-authentication-setup/two-factor-authentication-setup.tsx, src/features/task-manager/components/task-manager-toolbar/task-manager-toolbar.tsx, src/features/task-manager/components/task-manager-ui/task-manager-badge.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/543 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/549
=> [RUSH 21/05/2025] Resolve the sonarQube issues

src/features/auth/hooks/use-auth.tsx, src/features/auth/services/sso.service.ts, src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/big-calendar/services/calendar-services.ts, src/features/dashboard/component/dashboard-overview/dashboard-overview.tsx, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.tsx, src/features/email/component/email-list/email-list.tsx, src/features/finance/components/finance-revenue-expense-graph/finance-revenue-expense-graph.tsx, src/features/task-manager/components/task-details-view/editable-description.tsx, src/features/task-manager/components/task-manager-ui/task-manager-badge.tsx, src/features/task-manager/hooks/use-card-tasks.tsx, src/pages/auth/signin/signin-sso.tsx, src/pages/email/email.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/543
=> [RUSH 23/05/2025] Resolve the left over sonarQube issues 

src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/email/component/email-list/email-list.tsx, src/features/finance/components/finance-revenue-expense-graph/finance-revenue-expense-graph-tooltip.tsx, src/features/finance/components/finance-revenue-expense-graph/finance-revenue-expense-graph.tsx, src/features/task-manager/components/task-manager-ui/task-manager-badge.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/543
=> [RUSH 23/05/2025] Resolve the sonarQube issues

src/features/chat/components/chat-contact-item/chat-contact-item.spec.tsx, src/features/chat/components/chat-contact-item/chat-contact-item.tsx, src/features/chat/components/chat-input/chat-input.tsx, src/features/chat/components/chat-profile/chat-profile.tsx, src/features/chat/components/chat-search/chat-search.spec.tsx, src/features/chat/components/chat-search/chat-search.tsx, src/features/chat/components/chat-sidebar/chat-sidebar.tsx, src/features/chat/components/chat-users/chat-users.spec.tsx, src/features/chat/components/chat-users/chat-users.tsx, src/features/chat/components/chat/chat.tsx, src/features/chat/components/modals/edit-group-name/edit-group-name.spec.tsx, src/features/chat/components/modals/forward-message/forward-message.spec.tsx, src/features/chat/components/modals/forward-message/forward-message.tsx
Close https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/658
=> [RUSH 19/06/25] Resolve the sonarqube issues

src/features/chat/components/chat-sidebar/chat-sidebar.tsx, src/features/chat/components/chat/chat.tsx, src/features/chat/components/modals/edit-group-name/edit-group-name.tsx, src/features/chat/data/chat.data.ts, src/features/invoices/components/invoice-items-table/invoice-items-table.tsx, src/features/invoices/components/invoice-preview/invoice-preview.tsx, src/features/invoices/components/invoices-detail/invoices-detail.spec.tsx, src/features/invoices/components/invoices-detail/invoices-detail.tsx, src/features/invoices/components/invoices-table-column/invoices-table.column.tsx, src/features/invoices/data/invoice-data.ts, tailwind.config.js
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/653 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/652 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/651 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/650 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/648 https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/649
=> [RUSH 20/06/2025] Resolved Invoices bug and unit testing

src/features/inventory/component/advance-data-table/advance-data-table.tsx, src/features/inventory/component/advance-expand-row-content/advance-expand-row-content.tsx, src/features/inventory/component/advance-inventory-details/advance-inventory-details.tsx, src/features/inventory/component/advance-table-columns/advance-table-columns.tsx, src/features/inventory/component/inventory-form/inventory-form.tsx, src/features/inventory/services/inventory.service.ts, src/lib/graphql-client.ts
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/706
=> [RUSH 21/07/2025] Resolve sonarQube issues in inventory

src/features/inventory/component/advance-expand-row-content/advance-expand-row-content.tsx, src/features/inventory/component/advance-inventory-details/advance-inventory-details.tsx, src/features/inventory/component/inventory-form/inventory-form.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-react-blocks-construct/issues/706
=> [RUSH 21/07/2025] Resolved sonarQube issue in the Inventory

package.json, src/config/api.ts, src/features/auth/components/signin-form/signin-form.tsx, src/features/auth/components/sso-signin-card/sso-signin-card.tsx, src/features/auth/services/auth.service.ts, src/features/auth/services/sso.service.ts, src/features/big-calendar/components/modals/add-event/add-event.tsx, src/features/big-calendar/components/modals/edit-recurrence/edit-recurrence.tsx, src/features/big-calendar/hooks/use-calendar-events.ts, src/pages/auth/auth-layout.tsx, src/pages/auth/verify-otp-key/verify-otp-key.tsx, src/utils/uuid.js
Closes https://github.com/SELISEdigitalplatforms/l3-nextjs-blocks-app/issues/1357 https://github.com/SELISEdigitalplatforms/l3-nextjs-blocks-app/issues/1339
=> [RUSH 16/09/2025] Authenticate SSO Mfa flow integration and crypto bug fixes

src/i18n/i18n.ts
Closes https://github.com/SELISEdigitalplatforms/l3-nextjs-blocks-app/issues/1457
=> [RUSH 29/09/2025] Integrate Key & Text mode toggling w.r.t UILM extension

src/features/auth/components/forgot-password/forgot-password.spec.tsx, src/features/auth/components/reset-password/reset-password.spec.tsx, src/features/chat/components/chat-contact-item/chat-contact-item.tsx, src/features/chat/components/chat-search/chat-search.tsx, src/features/chat/components/modals/forward-message/forward-message.spec.tsx, src/features/chat/components/modals/forward-message/forward-message.tsx, src/features/dashboard/component/dashboard-user-activity-graph/dashboard-user-activity-graph.spec.tsx, src/features/file-manager/components/file-manager-add-new-dropdown.tsx, src/features/file-manager/components/modals/rename-modal.tsx, src/features/iam/components/add-profile/add-profile.spec.tsx, src/features/invoices/components/invoice-preview/invoice-preview.tsx, src/features/task-manager/components/card-view/column-menu.tsx, src/pages/chat/chat.spec.tsx, src/pages/main/main-layout.spec.tsx, src/pages/profile/profile.spec.tsx, src/pages/services/mail/mail.spec.tsx
Closes https://github.com/SELISEdigitalplatforms/l3-nextjs-blocks-app/issues/1542
=> [RUSH 08/10/2025] Fixed Vitest warning issue on hydration errors and Shadcn component warning message
